icon_include_package: jsk_rviz_plugins

rviz_service_call:
    buttons:
    - {icon: reset-pose.jpg, service_name: "/target", text: "Reset Pose"}
    - {icon: reset-manip-pose.jpg, service_name: "/target2", text: "Reset Manip"}
    - {icon: init-pose.jpg, service_name: "/target3", text: "Init Pose"}